### ISSUE TITLE
Some URLs are invalid for variable fonts from Google Fonts. No support of font variables in general.

### ISSUE THREAD

**Issue by andriytyurnikov** [seek-oss/capsize#186]
<img width="1024" alt="Screenshot 2024-03-23 at 18 44 29" src="https://github.com/seek-oss/capsize/assets/3668/f5d4f3f3-580b-492c-8cdd-83bd70254a99">

As Google Fonts exposes variables for Variable Fonts in URLs, it might be nice to have support for those.
URLs like: `https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,100..1000`

**Comment by michaeltaranto** [comment]
The issue here might be slightly confusing. The provided URL is a link to a stylesheet, but this field expects a link to a web font file. So in this case supplying the font file from the stylesheet seems to work fine:
```
https://fonts.gstatic.com/s/robotoflex/v26/NaNNepOXO_NexZs0b5QrzlOHb8wCikXpYqmZsWI-__OGbt8jZktqc2V3Zs0KvDLdBP8SBZtOs2IifRuUZQMsPJtUsR4DEK6cULNeUx9XgTnH37Ha_FIAp4Fm0PP1hw45DntW2x0wZGzhPmr1YNMYKYn9_1IQXGwJAiUJVUMdN5YUW4O8HtSoXjC79QRyaLshNDUf3e0O-gn5rrZCu20YNau4OPFu02G5.woff2
```

Alternatively searching for `Roboto Flex` from the “Google Fonts” tab in Step 1.
