### ISSUE TITLE
Please add support for M PLUS Rounded 1c from Google Fonts

### ISSUE THREAD

**Issue by mwawrusch** [seek-oss/capsize#189]
Getting some warnings for the font `M PLUS Rounded 1c` in 14.2.0. See this thread in next: https://github.com/vercel/next.js/issues/47115#issuecomment-2051755660

```
import { M_PLUS_Rounded_1c } from "next/font/google";
```

Would be amazing if you could add this font. Thank you

**Comment by michaeltaranto** [comment]
Will do mate.

Have been focused on getting weight and variant support and haven't updated Google Fonts.

I'll resolve/close this issue when it's done.

**Comment by mwawrusch** [comment]
Thank you, much appreciated.

**Comment by michaeltaranto** [comment]
@mwawrusch I am a little bit confused actually. I have just run the scripts to update to the latest Google Fonts (see #190), and `M PLUS Rounded 1c` has not been added to the metrics.

Interestingly, its not even in the Google Fonts [API response] 🤔

[API response]: https://github.com/seek-oss/capsize/blob/e8ff72fb8083c2e96002ae7686289a6864e93113/packages/metrics/scripts/source-data/googleFontsData.json#L18605-L18708

**Comment by michaeltaranto** [comment]
Bit of a deep dive. Ended up not related to our Google Fonts being behind, but rather that this particular font uses a different name for itself in its internal metrics, resulting in the module path not being as predictable as we'd like: `@capsizecss/metrics/roundedMplus1c`.

Made a change on our side to ensure our module paths always match the font name used by Google Fonts (rather than the internal metrics).

Given this changes the module path for about 20 fonts, we are treating it as a breaking change, but likely wont affect many.
