### ISSUE TITLE
Question: Determining the font metrics without referencing to capsize website

### ISSUE THREAD

**Issue by Namchee** [seek-oss/capsize#25]
Hi,

First of all amazing work! Now I can sleep in peace knowing that my paragraph is being spaced properly.

I have a question about determining the font metrics used by `capsize`, is it possible to obtain those without going through the website? I've tried comparing the metrics on capsize website and metrics generated by [this tool](https://github.com/soulwire/FontMetrics), but it's vastly different. (am I missing something crucial here?)

Cheers

**Comment by DylanVann** [comment]
You can use https://github.com/seek-oss/capsize/blob/master/packages/capsize/src/metrics.ts.

Compiled JS for it is not published at the moment though, it's imported directly on the website: https://github.com/seek-oss/capsize/blob/7a8e14f33d2151f292744cd9ea82215168b6f5cc/site/src/components/FontSelector/GoogleFontSelector.tsx#L3

**Comment by michaeltaranto** [comment]
Yeah sorry i started looking into this on my phone and never followed up. I wanted to look at how they compute their metrics so that i could better respond to your original question about the differences. Have not had a chance to do this.

In terms of getting the metrics without the website, i am planning to expose some of these utilities, just have not got back to it yet. Hopefully soon.

**Comment by Namchee** [comment]
Thank you for your response!

Unfortunately, the proposed solution only works when the font file is supplied. Any chance to do this on system font stack?

**Comment by michaeltaranto** [comment]
See https://github.com/seek-oss/capsize/issues/23#issuecomment-673743474

**Comment by Namchee** [comment]
Since I need metrics for system font-stack, I'll move the discussion to #23
